### PR TITLE
add AddMatchSignal method

### PR DESCRIPTION
**Pull request by kovetskiy**

### CODE REVIEW

**Comment by philips** [comment]
Is there a reason to call it subscribe instead AddMatchSignal or something?

**Comment by kovetskiy** [comment]
@philips I think name it's not such necessary. I can change to AddMatchSignal, if you want.

**Comment by kovetskiy** [comment]
@philips any reaction?

**Comment by philips** [comment]
AddMatchSignal makes the most sense to m.e

**Comment by jonboulle** [comment]
+1

**Comment by kovetskiy** [comment]
@philips @jonboulle fixed

**Comment by jonboulle** [comment]
LGTM

**Comment by pdf** [comment]
Was this not added to the `BusObject` interface so as not to break compatibility?  Because most functions that provide an Object have a return type of BusObject, the result is that using this method currently requires type assertion for most workflows.

**Pull request merged**
