### PR TITLE
transport_unix.go: return err instead of nil

### PR DESCRIPTION
**Pull request by QuentinPerez**

### CODE REVIEW

**Comment by philips** [comment]
@QuentinPerez Does this fix a bug? Can you write a test to exercise?

**Comment by philips** [comment]
ping

**Comment by easyrasta** [comment]
you should close this pr it's already done.

**Comment by jsouthworth** [comment]
It looks like the error that is being returned from EncodeTo is still nil. It has just moved down a few lines due to the merge from #100. This should probably be fixed as it is just erasing an error which may be present.

**Pull request closed without merging**
