### PR TITLE
Add a context to connections

### PR DESCRIPTION
**Pull request by jhenstridge**
This PR attaches a context to D-Bus connections.  It adds a `WithContext(ctx)` option to the connection constructor to set a parent context for the connection (overriding a default of `context.Background()`), and adds a `Conn.Context` method to retrieve the connection's context.  The connection's context will be done when either the parent context is done, or a disconnect is detected.  In either case, the connection is closed when the context is done.

The use cases for this are:

1. by setting a parent context for a connection, it can automatically be cleaned up with related code.

2. by monitoring the context of the shared `SessionBus` or `SystemBus` connections, it is possible to have a daemon exit cleanly when the bus exits (e.g. on user session shutdown).

3. while it isn't implemented in this PR, the context could be used to derive one passed to server methods.

### CODE REVIEW

**Comment by amenzhinsky** [comment]
I think a context should only affect the dialing process, it's something that is passed along with each blocking call rather than assigned to a client entirely.

**Comment by jhenstridge** [comment]
The main uses I see for having a context attached to the connection itself are:

1. provide a way to signal that the D-Bus connection has been closed.  Depending on the application, you might want to exit on this condition, or try to reconnect to the bus and re-export services, etc.
2. provide a parent for contexts assigned to incoming method calls.  Contexts are useful for serving incoming calls, since (a) it can be used to assign deadlines and (b) they can be used as a context for outgoing method calls required to service the request (e.g. a server performing a call-out to polkitd to authenticate its client).

You could probably do a custom disconnect reporting API for (1), but when you add (2) to the mix it seems like `Context` is a natural fit.

**Comment by jsouthworth** [comment]
@jhenstridge Those use cases make sense to me. Do you it make sense to have different contexts for each blocking call as @amenzhinsky suggests?  Is there a way to have those contexts depend on the conn's context so that if it is cancelled they are also cancelled?

**Comment by amenzhinsky** [comment]
I do agree that we need to have ability to pass contexts for both dial and close methods where we need to able to control timeouts and set deadlines, for example TCP dialing can block almost indefinitely (for this we may add an option that configures context-aware [dialer](https://golang.org/pkg/net/#Dialer.DialContext)), meaning we pass separate contexts for every blocking call.

But I haven't seen code that would assign a global context to a client (see `database/sql` or [amqp](github.com/vcabbage/amqp) as an example of a good-written library), if you could provide an example that does that or makes use of it, please post a link here.

For tracking disconnects I'd recommend to add something like:

```
func (c *Conn) Done() <-chan struct{} {
	return c.done
}

func (c *Conn) Err() error {
	return c.err
}
```

Because the error that caused a disconnect can be anything `EOF`, `Connection lost`, etc,  not only `context.Canceled` or `context.DeadlineExceeded`.

**Comment by jhenstridge** [comment]
> Do you it make sense to have different contexts for each blocking call as @amenzhinsky suggests? Is there a way to have those contexts depend on the conn's context so that if it is cancelled they are also cancelled?

Under normal conditions, connecting to the bus is usually instant.  Being disconnected from the bus is more common (at least once per login session), which is why I focused on that.

If you are using the D-Bus protocol in an unusual way, the part of this patch allowing you to set a parent context for the connection's context when creating private connections could be useful.  If we switched from `Dial` to `DialContext`, and passed the connection's context, it would be possible to abort the connection attempt by cancelling the parent context.

I'm not sure whether there is a specific need to have a separate context just for this action though.

> if you could provide an example that does that or makes use of it, please post a link here.

For my particular use case, I'm using the [Tomb](https://gopkg.in/tomb.v2) package to manage lifecycle of one component that owns a private D-Bus connection where I export an API on thr bus.  Attaching the connection to the tomb's context would provide a way to automatically clean up with the rest of the server.

Looking on godoc.org, I also found an OpenID Connect server that allows the caller to provide a context to control the lifecycle of background tasks it performs:

https://godoc.org/github.com/dexidp/dex/server

One issue is that any API designed prior to the existence of contexts is likely to roll their own cancellation system.  That doesn't necessarily mean that their custom solution is better than one using the standard library.

**Comment by jsouthworth** [comment]
Ok, I see the value of having this as an option. I also don't see any harm in adding in this functionality. I'm going to merge this. Thanks!

**Pull request merged**
