### PR TITLE
Add FreeBSD transport_unixcred

### PR DESCRIPTION
**Pull request by aperum**
This is essentially a copy of the DragonFly version with a few patches to make it work on FreeBSD (tested on 10.3 AMD64). Whoever did the DragonFly version should get all the credit.

### CODE REVIEW

**Comment by mdlayher** [comment]
I would love to see this go in so that we can build `torusblk` on FreeBSD as well.

**Comment by jsouthworth** [comment]
Is there a reason not to try to get the FreeBSD credential passing into the go standard library? This feels like the wrong place to implement credential passing to me. That said, I don't feel strongly that it can't be done here if others are OK with the change.

**Comment by aperum** [comment]
As this patch uses C includes i don't think it is fit for inclusion into Go itself. It would take someone with knowledge of the FreeBSD ucred implementation and varying sizes for i386, amd64, ... . I think there is no harm in implementing it here for the time being. If support for this is committed to golang.org/x/sys/ (because syscall is in lock down) it can be easily deleted again.

**Comment by tomoyat1** [comment]
Are there any plans to merge this here?
I'd like it to try and get a recent version of docker workng on FreeBSD 12-CURRENT.

**Comment by jsouthworth** [comment]
@tomoyat1  I'm ok with these changes. @aperum are these ready to merge?

**Comment by aperum** [comment]
I'm using these changes since i submitted them, so yes, i think they are ready to be merged.

**Pull request merged**
