### PR TITLE
system bus adress lookup was not system specific

### PR DESCRIPTION
**Pull request by krasi-georgiev**
Signed-off-by: Krasi Georgiev <krasi.root@gmail.com>

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
the test passes on my local machine

**Comment by jsouthworth** [comment]
The test failures don't look related to your change. I'll get that sorted out then review your changes in more detail.

**Comment by jsouthworth** [comment]
The tests are fixed. Can you rebase your changes onto the latest master? Thanks for your patience with this.

**Comment by krasi-georgiev** [comment]
all green 😄

**Comment by jsouthworth** [comment]
Looks good to me

**Pull request merged**
