### PR TITLE
Adding PPC64LE architecture

### PR DESCRIPTION
**Pull request by ezeeyahoo**
Hi,

I have added PPC64LE to arch to enable its support on Travis CI, request you to please review it.

Thanks

### CODE REVIEW

**Comment by jsouthworth** [comment]
@jhenstridge, I believe you last looked at the multiarch support. Care to comment here? Thanks!

**Comment by jhenstridge** [comment]
It looks like the current multi-arch tests stopped running some time between these two runs:

https://travis-ci.org/github/godbus/dbus/builds/650661763
https://travis-ci.org/github/godbus/dbus/builds/675333436

There was no change to the `.travis.yml` file between those runs, so presumably something changed on Travis's end.  The existing multiarch tests depend on Qemu's Linux user space emulation to run the tests on an x86 VM, since I don't think Travis was offering non-x86 runners at the time.

Given that Qemu's emulation isn't perfect, you may as well drop the current hacks and use Travis's native multi-arch.  It seems a bit wasteful to do a full cross product of Go versions and architectures, so maybe something like this would be appropriate:

```
arch:
  - amd64
go:
  - 1.13.x
  - 1.12.x
  - 1.11.x
  - tip
matrix:
  fast_finish: true
  allow_failures: 
    - go: tip
  include:
    - arch: amd64
      env: GOARCH=386
    - arch: arm64
    - arch: arm64
      env: GOARCH=arm
    - arch: ppc64le
```

If I'm [reading the docs right](https://docs.travis-ci.com/user/multi-cpu-architectures), these additional jobs would use the first value for `go:` variable, so you'd want to make sure the most recent stable release is listed first.

**Comment by jsouthworth** [comment]
I've switched this repo to travis-ci.com.

**Comment by jhenstridge** [comment]
There are a few more developments that might make switching to GH Actions worthwhile.  Travis is shifting Open Source projects over to a trial plan, with the option to beg for more credits when the trial credits expire:

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

And switching back to travis-ci.org isn't an option, since it is being shut down in December:

https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom

**Comment by jsouthworth** [comment]
> There are a few more developments that might make switching to GH Actions worthwhile. Travis is shifting Open Source projects over to a trial plan, with the option to beg for more credits when the trial credits expire:
> 
> https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
> 
> And switching back to travis-ci.org isn't an option, since it is being shut down in December:
> 
> https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom

I got that email from travis-ci last week. I've been meaning to learn how to switch this to GH actions but I haven't had the time yet.

**Comment by jsouthworth** [comment]
Well, porting to github actions for the default Go on Linux case was straight forward. I'll leave it to others to open PRs against .github/workflows/go.yaml if we want to do other things with it.

**Comment by jsouthworth** [comment]
I'm declining this PR due to switching to Github Actions. If it is possible to add architecture support to Github Actions and you'd still like to see this architecture tested, please reopen the PR against ".github/workflows/go.yml". Thanks!

**Pull request closed without merging**
