### PR TITLE
Fix singleton can no longer be used after being closed

### LINKED ISSUE #144: Errors with a new connection if previous was closed
In my code I use the following pattern
```
conn, err := dbus.SystemBus()
if err != nil {
	return nil, err
}
defer conn.Close()
```

And in the first function it works great, but the second function fails with error "dbus: connection closed by user". If I remove `defer conn.Close()` the both functions work great.

### PR DESCRIPTION
**Pull request by wzshiming**
Fixes #144

### CODE REVIEW

**Comment by bminer** [comment]
It might be nice to create a `Connected() bool` method for Conn that checks the Err() on the ctx. Thoughts?

**Comment by wzshiming** [comment]
> It might be nice to create a `Connected() bool` method for Conn that checks the Err() on the ctx. Thoughts?

Thanks, good suggestion, updated.

**Comment by wzshiming** [comment]
@jsouthworth
Hi, could you have time to take a look?

**Comment by jsouthworth** [comment]
Looks good. Can you add a test so we ensure we don’t break this in the future? Do we also need this for the SessionBus?

**Comment by wzshiming** [comment]
> Looks good. Can you add a test so we ensure we don’t break this in the future? Do we also need this for the SessionBus?

Thanks, updated.

**Comment by jsouthworth** [comment]
Looks good, thanks!

**Comment by wzshiming** [comment]
@jsouthworth 
Hi
Is there any plan to release v5.0.4 when?

**Pull request merged**
