### PR TITLE
Adds another example usage to readme

### PR DESCRIPTION
**Pull request by esiqveland**
As per #28, adds another example of usage to the README.

### CODE REVIEW

**Comment by bcwaldon** [comment]
@esiqveland Please squash your commits down to one, then LGTM

**Comment by philips** [comment]
@esiqveland ping

**Comment by esiqveland** [comment]
Sorry, I was on holiday. Don't know if you can edit commits after having pushed, so closing this and opening a new one.

**Comment by kyrofa** [comment]
Looks like you already opened another one, but future reference: Squashing is done via an [interactive git rebase](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History).

**Pull request closed without merging**
